#!/usr/bin/env python

from mcp import *

host = 'localhost'

serv = Client(host)
serv.connect()

if len(sys.argv) > 1:
	result = serv.ask(*sys.argv[1:])
	print result
else:
	prompt = '(pique)%s: ' % host
	import readline
	import shlex
	while True:
		try:
			cmd = shlex.split(raw_input(prompt))
			result = serv.ask(*cmd)
			print result
		except EOFError:
			break
