#!/usr/bin/env python

DEBUG = True

import sys, os
import pygtk, gtk, gobject
import pygst
pygst.require('0.10')
import gst

Element = gst.element_factory_make
def Bin(*elements):
	#elements = [e if not isinstance(e,str) else Element(e) for e in elements]
	bin = gst.Bin()
	if len(elements):
		bin.add(*elements)
		if len(elements)-1:
			gst.element_link_many(*elements)
		for t,d,i in (('sinks',gst.PAD_SINK,0),('srcs',gst.PAD_SRC,-1)):
			j = 0
			for pad in elements[i].pads():
				if pad.props.direction == d:
					bin.add_pad(gst.GhostPad(t[:-1] + str(j), pad))
					j+=1
	return bin
	
class MediaButtons(gtk.VBox):
	def __init__(self):
		gtk.VBox.__init__(self)
		self.toolbar = gtk.Toolbar()
		self.toolbar.set_orientation(gtk.ORIENTATION_HORIZONTAL)
		self.toolbar.set_show_arrow(False)
		
		self.play = gtk.ToolButton(gtk.STOCK_MEDIA_PLAY)
		self.toolbar.insert(self.play, -1)
		
		self.pause = gtk.ToolButton(gtk.STOCK_MEDIA_PAUSE)
		self.toolbar.insert(self.pause, -1)
		
		self.stop = gtk.ToolButton(gtk.STOCK_MEDIA_STOP)
		self.toolbar.insert(self.stop, -1)
		
		self.previous = gtk.ToolButton(gtk.STOCK_MEDIA_PREVIOUS)
		self.toolbar.insert(self.previous, -1)
		
		self.next = gtk.ToolButton(gtk.STOCK_MEDIA_NEXT)
		self.toolbar.insert(self.next, -1)
		
		self.position = gtk.Adjustment(step_incr=15)
		self.pos = gtk.ToolItem()
		self.pos.set_expand(True)
		self.pos.add(gtk.HScale(self.position))
		self.toolbar.insert(self.pos, -1)
		
		self.pack_start(self.toolbar, expand=True, fill=True)
		
	def connect(self, which, func, *extra):
		if which == 'play':
			self.play.connect('clicked', func, *extra)
		elif which == 'pause':
			self.pause.connect('clicked', func, *extra)
		elif which == 'stop':
			self.stop.connect('clicked', func, *extra)
		elif which == 'next':
			self.next.connect('clicked', func, *extra)
		elif which == 'previous':
			self.previous.connect('clicked', func, *extra)
		elif which == 'position':
			self.position.connect('value-changed', func, *extra)
		else:
			gtk.HButtonBox.connect(self, which, func, *extra)

class Main(object):
	def __init__(self, files):
		self.lib = library.library(library.DEFAULT_PATH)

		self.win = gtk.Window(gtk.WINDOW_TOPLEVEL)
		self.win.set_title('Video-Player')
		self.win.set_default_size(500, 400)
		self.win.connect('destroy', self.on_destroy, 'WM destroy')
		vbox = gtk.VBox()
		self.win.add(vbox)
		
		buttons = MediaButtons()
		buttons.connect('play', lambda b:self.play())
		buttons.connect('pause', lambda b:self.pause())
		buttons.connect('stop', lambda b:self.stop())
		buttons.connect('next', lambda b:self.next())
		buttons.connect('previous', lambda b:self.previous())
		buttons.connect('position', lambda a:self.seek(a.value, absolute=True, percent=False))
		
		self.movie_window = gtk.DrawingArea()
		vbox.pack_start(self.movie_window, True, True)
		vbox.pack_start(buttons, False, False)
		self.win.show_all()

		self.player = gst.element_factory_make('playbin2', 'player')
		self.player.connect('about-to-finish', self.on_about_to_finish)

		self.taginject = Element('taginject')
		audio_bin = Bin(self.taginject, Element('rgvolume'), Element('gconfaudiosink'))
		self.player.set_property('audio-sink', audio_bin)
		
		video_sink = Element('xvimagesink')
		video_sink.set_xwindow_id(self.movie_window.window.xid)
		video_sink.set_property('force-aspect-ratio', True)
		self.player.set_property('video-sink', video_sink)
		self.player.set_property('vis-plugin', Element('goom2k1'))
		
		self.playlist = iter(files)

		bus = self.player.get_bus()
		bus.add_signal_watch()
		bus.enable_sync_message_emission()
		bus.connect('message::eos', self.on_eos)
		bus.connect('message::error', self.on_error)
		
		self.on_about_to_finish(self.player)
		self.play()
		
	def seek(self, new, absolute=True, percent=False):
		format = gst.SEEK_TYPE_SET if absolute else gst.SEEK_TYPE_CUR
		if percent:
			new *= self.player.get_duration()
			
		self.player.seek_simple(format, gst.SEEK_FLAG_NONE, new)

	def play(self):
		if DEBUG: print 'play'
		self.player.set_state('playing')
		
	def pause(self):
		if DEBUG: print 'pause'
		self.player.set_state('paused')
		
	def stop(self):
		if DEBUG: print 'stop'
		self.player.set_state('null')
		
	def previous(self):
		if DEBUG: print 'previous'
		pass
		
	def next(self, *args):
		if DEBUG: print 'next'
		self.stop()
		self.load_next()
		self.play()
		
	def load_next(self):
		if DEBUG: print 'load_next'
		try:
			uri = self.playlist.next()
		except StopIteration:
			self.stop()
			return
		index = self.lib.index(uri)
		tags = self.lib[index]._asdict()
		self.player.set_property('uri', uri)
		self.taginject.props.tags = 'replaygain-reference-level=%s,replaygain-track-gain=%s,replaygain-track-peak=%s' % (tags['reference_level'], tags['gain'], tags['peak'])
		
	def quit(self):
		self.player.set_state('null')
		gtk.main_quit()
		
	def on_about_to_finish(self, player):
		self.load_next()
			
	def on_eos(self, bus, message):
		self.stop()
		
	def on_error(self, bus, message):
		self.stop()
		err, debug = message.parse_error()
		print "Error: %s" % err, debug
		
	def on_destroy(self, *args):
		self.quit()

if __name__=='__main__':
	import optparse
	import library
	
	parser = optparse.OptionParser(usage="%prog [songlist ...]", version="%prog 0:01")
	
	l = library.library(library.DEFAULT_PATH)
	p = []

	def my_callback(option, opt_str, value, parser):
		c = l.db.cursor()
		c.execute('select uri from media where %s=? order by artist,album,track_number' % opt_str[2:], (value,))
		for u in c:
			print u[0]
			p.append(u[0])

	parser.add_option('--album',
	callback=my_callback, action="callback", type="string",
	help="Include all songs in ALBUM in the playlist")
	parser.add_option('--artist',
	callback=my_callback, action="callback", type="string",
	help="Include all songs by ARTIST in the playlist")
	parser.add_option('--genre',
	callback=my_callback, action="callback", type="string",
	help="Include all songs in GENRE in the playlist")
	
	sys.argv = ['mcp-library','file:///home/ryan/Videos/Family Guy/4.01 North by North Quahog.avi']

	options, args = parser.parse_args()

	for a in args:
		p.append(a)

	m = Main(p)
	gtk.gdk.threads_init()
	gtk.main()
