#!/usr/bin/env python

from mcp import *
import optparse

sys.argv = ['mcp-library'] + \
['file:///home/ryan/Videos/Family Guy/%s' % f for f in os.listdir('/home/ryan/Videos/Family Guy')]

parser = optparse.OptionParser(usage="%prog [songlist ...]", version="%prog 0:01")

m = Main()

def my_callback(option, opt_str, value, parser):
	kwargs = {opt_str[2:]: value}
	for uri in m.lib.select_uris(**kwargs):
		print uri
		m.playlist.append(uri)

parser.add_option('--album', callback=my_callback, action="callback", type="string", help="Include all songs in ALBUM in the playlist")
parser.add_option('--artist', callback=my_callback, action="callback", type="string", help="Include all songs by ARTIST in the playlist")
parser.add_option('--genre', callback=my_callback, action="callback", type="string", help="Include all songs in GENRE in the playlist")
options, args = parser.parse_args()

for a in args:
	m.playlist.append(library.uri(a))

m.start()
print
