#!/usr/bin/env python

from mcp.client import Client

import sys
import time

host = 'localhost'

serv = Client(host)
serv.connect()

if len(sys.argv) > 1:
	result = serv.ask(*sys.argv[1:])
	print result
else:
	import readline
	import shlex
	import os
	prompt = '(pique)%s: ' % host if os.isatty(sys.stdin.fileno()) else ''
		
	while True:
		try:
			cmd = shlex.split(raw_input(prompt), True)
			if cmd:
				result = serv.ask(*cmd)
				print result
		except EOFError:
			break
	if os.isatty(sys.stdin.fileno()): print
