#!/usr/bin/env python

import optparse
import sys

args = sys.argv
sys.argv = []

from mcp import *

sys.argv = args

#sys.argv = ['mcp-library'] + \
#['file:///home/ryan/Videos/Family Guy/%s' % f for f in os.listdir('/home/ryan/Videos/Family Guy')]

parser = optparse.OptionParser(usage="%prog [songlist ...]", version="%%prog %s" % VERSION)

m = Main()

def my_callback(option, opt_str, value, parser):
	kwargs = {opt_str[2:]: value}
	for uri in m.lib.select_uris(**kwargs):
		print uri
		m.playlist.append(uri)

parser.add_option('--album', callback=my_callback, action="callback",
  type="string", help="Include all songs in ALBUM in the playlist")
parser.add_option('--artist', callback=my_callback, action="callback",
  type="string", help="Include all songs by ARTIST in the playlist")
parser.add_option('--genre', callback=my_callback, action="callback",
  type="string", help="Include all songs in GENRE in the playlist")

options, args = parser.parse_args()

for a in args:
	m.player.playlist.append(uri(a))

m.start()
print
