# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_REQUEST_REQUESTTYPE = descriptor.EnumDescriptor(
  name='RequestType',
  full_name='Request.RequestType',
  filename='RequestType',
  values=[
    descriptor.EnumValueDescriptor(
      name='PING', index=0, number=0,
      options=None,
      type=None),
  ],
  options=None,
)

_RESPONSE_ERRORCODE = descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='Response.ErrorCode',
  filename='ErrorCode',
  values=[
    descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UnknownCommand', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BadCredentials', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='IncorrectArgs', index=3, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


_REQUEST = descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename='mcp-rpc.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Type', full_name='Request.Type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Credentials', full_name='Request.Credentials', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Arguments', full_name='Request.Arguments', index=2,
      number=3, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _REQUEST_REQUESTTYPE,
  ],
  options=None)


_RESPONSE = descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename='mcp-rpc.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Err', full_name='Response.Err', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Explanation', full_name='Response.Explanation', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _RESPONSE_ERRORCODE,
  ],
  options=None)


_REQUEST.fields_by_name['Type'].enum_type = _REQUEST_REQUESTTYPE
_RESPONSE.fields_by_name['Err'].enum_type = _RESPONSE_ERRORCODE

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST

class Response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE


_MCP = descriptor.ServiceDescriptor(
  name='mcp',
  full_name='mcp',
  index=0,
  options=None,
  methods=[
  descriptor.MethodDescriptor(
    name='Play',
    full_name='mcp.Play',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
])

class mcp(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _MCP
class mcp_Stub(mcp):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _MCP

