#!/usr/bin/env python

from pique.client import Client
import sys

host = 'localhost' if len(sys.argv) == 1 else sys.argv[1]
serv = Client(host)
serv.connect()

if len(sys.argv) > 1:
	result = serv.ask(*sys.argv[1:])
	print result
else:
	import readline
	import shlex
	import os
	tty = os.isatty(sys.stdin.fileno())
	prompt = '(pique)%s: ' % host if tty else ''
		
	while True:
		try:
			cmd = raw_input(prompt)
			if cmd:
				result = serv.ask(*shlex.split(cmd,True))
				print result
		except EOFError:
			break
		except KeyboardInterrupt:
			break
	if tty: print
